version: "3.5"
name: example
services:
  db:
    image: arm64v8/mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'strongforce'
      MYSQL_USER: 'strongforce'
      MYSQL_PASSWORD: 'strongforce'
      MYSQL_ROOT_PASSWORD: 'strongforce'
    ports:
      - '64001:3306'
    expose:
      - '64001'
  nats:
    image: nats:2.10
    ports:
      - "64002:4222"
    command:
      - "-js"
